import { readFile } from "node:fs/promises";
import path from "node:path";
import { NextRequest, NextResponse } from "next/server";
import { apiRequireNonClient } from "@/lib/guard";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

/**
 * Serves the chime WAVs that the Python telegram-voice service
 * generates into `telegram-voice/sounds/`. The whole point is that
 * the dashboard and the Telegram call stream the *exact same file*
 * — same acoustic design, same amplitude, same sample rate — so the
 * user hears an identical "your turn" cue whether they're on the
 * phone or on the laptop. Re-synthesizing a second recipe in Web
 * Audio was the obvious alternative, but any drift between the two
 * shows up as a jarring "this doesn't sound like the phone one"
 * the first time you switch mid-conversation.
 *
 * The Python service writes these files at startup (see
 * `_prewarm_feedback_sounds` in service.py). If the Python service
 * has never run on this box the files are missing — in that case we
 * return 404 and the client's useChime hook silently skips. No
 * need for a noisy error; a missing chime is a papercut, not a bug
 * worth breaking the voice flow over.
 *
 * Allowed files are an explicit whitelist so the route can't be
 * abused to read arbitrary paths out of the project tree.
 */

const ALLOWED = new Set([
  "your_turn.wav",
  "thinking_chime.wav",
  // `thinking_hum.wav` was the previous 90/93 Hz drone. Kept on the
  // whitelist so stale clients with cached HTML still get a graceful
  // 404 (vs. a 400) if they ask for it after a deploy — the Python
  // side no longer generates it either way.
  "thinking_hum.wav",
  // One-shot "assistant started thinking" cue — plays on the busy
  // edge, distinct from the looping thinking_chime. Generated by
  // _thinking_start_chime_path in service.py.
  "thinking_start.wav",
  "accept.wav",
  "end.wav",
  "dial.wav",
  // Brief warm "message launched" tone played the instant the user
  // submits a turn — same WAV used on the Telegram leg by the Python
  // worker (recipe in service.py: _message_sent_chime_path).
  "message_sent.wav",
]);

const SOUND_ROOT = path.resolve(process.cwd(), "telegram-voice", "sounds");

export async function GET(
  _req: NextRequest,
  ctx: { params: Promise<{ file: string }> },
): Promise<NextResponse> {
  const auth = await apiRequireNonClient();
  if (!auth.ok) return auth.res;
  const { file } = await ctx.params;
  if (!ALLOWED.has(file)) {
    return new NextResponse("not allowed", { status: 400 });
  }
  const target = path.join(SOUND_ROOT, file);
  // Defence-in-depth against a future ALLOWED entry sneaking in a
  // slash. path.join would normalize it but the resolve check catches
  // any case where the final path escapes SOUND_ROOT.
  if (!target.startsWith(SOUND_ROOT + path.sep)) {
    return new NextResponse("not allowed", { status: 400 });
  }
  let buf: Buffer;
  try {
    buf = await readFile(target);
  } catch {
    return new NextResponse("not generated yet — start telegram-voice once", {
      status: 404,
    });
  }
  return new NextResponse(new Uint8Array(buf), {
    status: 200,
    headers: {
      "Content-Type": "audio/wav",
      // Chimes never change after first generation; cache aggressively
      // so the browser never re-fetches on repeat plays.
      "Cache-Control": "public, max-age=3600, immutable",
    },
  });
}

